// This file was autogenerated by notion-simple-cli
// don't edit below this lineimport { RichText } from './classes';
import { BaseCollectionPage } from "./classes/base-collection-page";
import { PageObjectResponse } from "./classes/notion-api-endpoints";
import { Select } from "./classes/select";

export type CollectionPageBlog = {
  likes: number;
  tags: Array<Select>;
  createdAt: Date;
  publishedAt: Date;
  isPublished: boolean;
  author: string;
  editedAt: Date;
  locale: Select;
  slug: string;
  isProtected: boolean;
  summary: string;
  universalSlug: string;
  name: string;
};
