import _ from 'lodash';
import fs from 'fs';
import { RichText } from '../classes';
import {
  DatabaseObjectResponse,
  DatabasePropertyConfigResponse,
} from '../classes/notion-api-endpoints';

const TYPES_DIR = './src/classes';
const PAGE_NAME_PREFIX = 'CollectionPage';
const CONSTRUCTOR = `
  constructor(pageObject: PageObjectResponse | PartialPageObjectResponse) {
    super(pageObject);
  }
`;

const WARNING = `
  // This file was autogenerated by notion-simple-cli
  // don't edit below this line\n`;
const BASE_IMPORT_STATEMENTS = fs.readFileSync(`${TYPES_DIR}/base-imports.ts`);

export const TYPE_MAP = {
  created_time: 'Date',
  last_edited_time: 'Date',
  date: 'Date',
  rich_text: 'RichText',
  title: 'RichText',
  number: 'number',
  select: 'Select',
  multi_select: 'Array<Select>',
  checkbox: 'boolean',
};

/**
 * Given the properties of a collection, it maps their types to a
 * Typescript type string definition.
 * @param property Property
 * @returns string
 */
export function mapCollectionProperties(
  propertyConfig: Record<string, DatabasePropertyConfigResponse>
) {
  return _.join(
    _.map(
      propertyConfig,
      (property) => `${_.camelCase(property.name)}: ${TYPE_MAP[property.type]};`
    ),
    '\n'
  );
}

export class Collection {
  id: string;
  createdTime: Date;
  lastEditedTime: Date;
  title: RichText;
  description: RichText;
  url: string;
  properties: Record<string, DatabasePropertyConfigResponse>;

  constructor(colObj: DatabaseObjectResponse) {
    this.id = colObj.id;
    this.createdTime = new Date(colObj.created_time);
    this.lastEditedTime = new Date(colObj.last_edited_time);
    this.url = colObj.url;
    this.title = new RichText(colObj.title);
    this.description = new RichText(colObj.description);
    this.properties = colObj.properties;
  }

  getCollectionClassName = (prefix: string = ''): string => {
    return prefix + _.upperFirst(_.camelCase(this.title.plainText));
  };

  getPropertiesTypeDefinition = (): string => {
    let className = this.getCollectionClassName(PAGE_NAME_PREFIX);
    let typeDefinition = `
    ${WARNING}
    ${BASE_IMPORT_STATEMENTS}
    export class ${className} extends BaseCollectionPage {
      ${mapCollectionProperties(this.properties)}

      ${CONSTRUCTOR}
    };`;
    return typeDefinition;
  };
}
