// This file was autogenerated by notion-simple-cli
// don't edit below this line

import { RichText } from './rich-text';
import { BaseCollectionPage } from './collection-page-base';
import { PageObjectResponse, PartialPageObjectResponse, QueryDatabaseBodyParameters } from './notion-api-endpoints';
import { Select } from './select';
import { NotionClient } from '../client';

export class Blog extends BaseCollectionPage {
  likes: number;
  tags: Array<Select>;
  createdAt: Date;
  publishedAt: Date;
  isPublished: boolean;
  author: RichText;
  editedAt: Date;
  locale: Select;
  slug: RichText;
  isProtected: boolean;
  summary: RichText;
  universalSlug: RichText;
  name: RichText;

  constructor(pageObject: PageObjectResponse | PartialPageObjectResponse) {
    super(pageObject);
  }

  getCollectionPages = async (databaseId: string, query?: QueryDatabaseBodyParameters): Promise<Blog[]> => {
    const notion = new NotionClient(process.env.NOTION_SECRET);
    try {
      const response = await notion.databases.query({
        database_id: databaseId,
        ...query,
      });
      return response.result.map((e: any) => new Blog(e));
    } catch (err) {
      console.error(err);
    }
  };
}
