// This file was autogenerated by notion-simple-cli
// don't edit below this line

import { RichText } from "./rich-text";
import { BaseCollectionPage } from "./collection-page-base";
import {
  PageObjectResponse,
  PartialPageObjectResponse,
} from "./notion-api-endpoints";
import { Select } from "./select";

export class Work extends BaseCollectionPage {
  likes: number;
  tags: Array<Select>;
  publishedAt: Date;
  from: Date;
  isPublished: boolean;
  author: RichText;
  location: RichText;
  to: Date;
  locale: Select;
  slug: RichText;
  isProtected: boolean;
  summary: RichText;
  universalSlug: RichText;
  name: RichText;

  constructor(pageObject: PageObjectResponse | PartialPageObjectResponse) {
    super(pageObject);
  }
}
